^TITLE ""
^QUESTION ZZZZZZOK
<DIV ALIGN=CENTER><B>Embry-Riddle Faculty &amp; Staff Climate Survey<BR></B>
<B>Spring 2002 </B>
<BR></DIV>
<TABLE CELLPADDING=1 COLS=1>
<TR ALIGN=LEFT VALIGN=TOP>
<TD WIDTH=725>         </TD></TR>
</TABLE>
<DIV ALIGN=CENTER>Thank You for Your Time and Assistance!
   <BR></DIV>
^GET OK 
^HIDE-RESERVED-QUESTIONS
^^reserved field names for collecting Internet information about respondent
^QUESTION HTTP_USER_AGENT
The code name of the browser used to complete the survey.
^GET QUOTE
^QUESTION REMOTE_ADDR
The remote address identified by the web server.
^GET QUOTE
^QUESTION REMOTE_HOST
The remote host identified by the web server.
^GET QUOTE
^QUESTION REMOTE_NAME
The remote name identified by the web server.
^GET QUOTE
^QUESTION REMOTE_USER
The remote user identified by the web server.
^GET QUOTE
^QUESTION EMAIL_DATE_RECEIVED
The date this survey was submitted.
^GET QUOTE
^QUESTION EMAIL_ADDRESS_RECEIVED_FROM
The e-mail address the survey was sent from.
^GET QUOTE
^QUESTION TEXT_EMAIL_VALIDATION_ERRORS
Any errors found when parsing the text e-mail response file.  You should manually verify that the answers are stored correctly.  Choices and topics need to fit on single lines (unseparated by carriage returns).
^GET QUOTE
^QUESTION TEXT_EMAIL_RESPONSE
The entire response file for this record (for e-mail text responses only).
^GET QUOTE
